### PR TITLE
i18n work by Compute Canada

### PR DESCRIPTION
**Pull request by usask-rc**
- Changing hard coded strings to message keys
- Adding French translations

### CODE REVIEW

**Comment by jimPruyne** [comment]
Hi Guys,

I've freed up some time to review this, and hopefully open us up to bringing in further changes you may have done. 

In review-metadata.jsp, there are references to `UIUtil.getLocalizedValue()` and that method doesn't seem to exist in the class. Is it possible that a diff there failed to get added?

Also, in doing the merge, besides goauth-related things which were removed, there was a conflict in navbar-minimal.jsp where I'd done an update based on the change in login flow and you guys had added the localized message for the "Log In" string. Easy conflict to resolve, but perhaps if you're updating this branch/PR you could include it so that my merge onto this branch can go away.

**Comment by usask-rc** [comment]
There is a diff that we have related to UIUtil.getLocalizedValue() but it's in the dspace source tree, not Globus source.  So I guess that's a bigger issue, related to the way that Globus Publication is built with two source trees.  Not really sure how to address this.

**Comment by jimPruyne** [comment]
> There is a diff that we have related to UIUtil.getLocalizedValue() but it's in the dspace source tree, not Globus source. So I guess that's a bigger issue, related to the way that Globus Publication is built with two source trees. Not really sure how to address this.

In the general case, what I do is copy the file from the dspace source into this repo with the exact same path, etc. and then apply my diffs/make changes/whatever. The build script in bin/dspace-build.sh will notice it, do renames, make symlinks, etc. In retrospect it isn't the solution I wish I'd gone with from the beginning, but it does work ok.

In this particular case, there's already a `GlobusUIUtil.java` which seems like it might be a reasonable home for this particular method. It is sort of a catch-all file which isn't my favorite thing, but then again so is the original `UIUtil` from dspace. So, I think adding it to `GlobusUIUtil` is probably the way to go. I don't immediately see how `getLocalizedValue` differs from `getLocalizedMessage` so I'm not sure I could re-create the functionality right away.

**Comment by usask-rc** [comment]
Agreed, we normally do the same (copy file to GP source then modify).  With this function, I don't remember why Adam didn't do that, I'll ask.

**Comment by jimPruyne** [comment]
Sounds good. I usually prefer not bringing in more source files if not needed. In this case, as long as the needed method is pretty much independent of the rest of the UIUtil class/file, I'd just as soon move it to GlobusUIUtil.

**Comment by usask-rc** [comment]
We'll move this method to the GlobusUIUtil file and update the PR

**Comment by usask-rc** [comment]
OK should be it.  I can't comment on the conflicts, it's been a year since we opened this PR, a lot has changed in your tree and ours since then.

**Pull request merged**
